# Generated by Django 3.2.8 on 2021-10-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.car', verbose_name='Машина'),
            preserve_default=False,
        ),
    ]
