# Generated by Django 3.2.8 on 2021-11-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_car_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avatar',
        ),
    ]
