# Generated by Django 3.2.8 on 2021-12-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_auto_20211103_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_kz',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_kz',
            field=models.CharField(max_length=30, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='webapp.platform', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Vol'),
        ),
        migrations.AlterField(
            model_name='client',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='message',
            field=models.CharField(max_length=3000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='HeightPla'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='length',
            field=models.PositiveSmallIntegerField(verbose_name='LongPla'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='width',
            field=models.PositiveSmallIntegerField(verbose_name='WidthPla'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.car', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Review'),
        ),
    ]
